name: GDScript 规范校验
# 触发：所有推送、所有PR
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # 1.拉取仓库代码
      - uses: actions/checkout@v4
      # 2.一键加载gdscript工具集（无需手动装Python/pip）
      - uses: Scony/godot-gdscript-toolkit@master
      # 3.检查所有gd脚本格式（--check只检查，不自动修改，失败则流水线标红）
      - name: 格式化规范检查 gdformat
        run: gdlint scripts/ --disable class-definitions-order,max-file-lines,unused-argument,max-returns,no-elif-return,no-else-return,function-variable-name
      # 4.代码规范、质量静态检测
      - name: 代码规范校验 gdlint
        run: gdlint scripts/
